name: nf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - numpy=1.26.3
  - pandas=2.2.3
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - scipy=1.13.1
  - scikit-learn=1.5.2
  - tqdm=4.66.6
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pillow=10.2.0
  - segmentation-models-pytorch=0.3.4
  - grad-cam=1.5.4
  - efficientnet-pytorch=0.7.1
  - timm=0.9.7
  - pretrainedmodels=0.7.4
  - ttach=0.0.3
  - torchsummary=1.5.1
  - sympy=1.13.1
  - jupyterlab
  - ipykernel
  - traitlets
  - setuptools
  - pip
  - pip:
    - safetensors
    - stringzilla
    - stringdist
    - simsimsd